
-- Data Preparation and Understanding

--Q: What is the total number of rows in each of the three tables in the database?

--Ans,
SELECT COUNT(*) FROM Customer$
UNION
SELECT COUNT(*) FROM TRANSACTIONS
UNION
SELECT COUNT(*) FROM PROD_CAT_INFO

--Q: What is the total number of transactions that have a return?

--Ans,
SELECT * FROM TRANSACTIONS
WHERE 
QTY<0
ORDER BY QTY

--Q: Convert the date variables into valid date formats before proceeding ahead?

--Ans3,
  SELECT CONVERT(VARCHAR(10),TRAN_DATE,3)CONVERTED_DATE_MONTH_YEAR FROM TRANSACTIONS
  SELECT CONVERT(VARCHAR(10),DOB,3)CONVERTED_DATE_MONTH_YEAR FROM Customer$

--Q: What is the time range of the transaction data available for the analysis? Show the output in nuber of days, months and years
--   simultaneously in different columns?

--Ans,
select DATEDIFF(day,min(convert(date,tran_date,3)),max(convert(date,tran_date,3)))Dte,
 DATEDIFF(month,min(convert(date,tran_date,3)),max(convert(date,tran_date,3)))Mth,
 DATEDIFF(year,min(convert(date,tran_date,3)),max(convert(date,tran_date,3)))Yr
from Transactions

--Q: Which product category does the sub-category 'DIY' belong to?

--Ans,
SELECT * FROM PROD_CAT_INFO
WHERE PROD_SUBCAT='DIY'

------------------------------------------------------------------------------------------------------------
--Data Analysis

--Q: Which channel is most frequently used for transactions?

--Ans, 
select store_type,count (Store_type) from transactions
group by Store_type
order by 2 desc

--Q: What is the count of Male and Female customers in the database?

--Ans, 
select gender,count(gender) from Customer$ 
group by Gender

--Q: From which city do we have the maximum number of customers and how many?

--Ans,
select city_code ,count(city_code) from Customer$
group by city_code
order by 2 desc

--Q: How many sub-categories are there under the Books category?

--Ans, 
select count(prod_subcat) from prod_cat_info
where 
prod_cat='books'
group by prod_subcat

--Q: What is the maximum quantity of products ever ordered?

--Ans,
select a.prod_cat_code,a.qty,b.prod_cat,count(b.prod_cat)Highest from Transactions a
left join prod_cat_info b on a.prod_cat_code=b.prod_cat_code
group by a.prod_cat_code,a.qty,b.prod_cat
order by Highest desc

--Q: What is the net total revenue generated in categories Electronics and Books?

--Ans,

select sum(total_amt)Amount
from Transactions a
join prod_cat_info b on a.prod_cat_code=b.prod_cat_code
and a.prod_subcat_code=b.prod_sub_cat_code
where 
prod_cat in('books','electronics')

--Q: How many customers have >10 transactions with us, excluding returns?

--Ans,

 select a.customer_Id,b.transaction_id,b.Qty from customer$ a
 left Join transactions b on a.customer_Id=b.cust_id
 WHERE 
 Qty > 10                

 --Q: What is the combined revenue earned from the 'Electronics' & 'Clothing' categories, from 'Flagship stores'?

 --Ans, 

 select sum(total_amt)Amount
 from Transactions a
 join prod_cat_info b on a.prod_cat_code=b.prod_cat_code
and a.prod_subcat_code= b.prod_sub_cat_code
 where
 prod_cat in('clothing','electronics') and Store_type='flagship store'

 --Q: What is the total revenue generated from 'Male' customers in 'Electronics' category? Output should display total revenue
 --   by prod_subcat.

 --Ans, Total revenue generated from 'Male' customers in 'Electronics' category is 21894260.0499999

 select sum(total_amt)Amount from Transactions a
 join Customer$ b on a.cust_id=b.customer_Id
 join prod_cat_info c on a.prod_subcat_code=c.prod_sub_cat_code
 where 
 gender='M' and prod_cat='Electronics'

 --Q: What is the percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
 
 --Ans,
 select top 5 prod_subcat,(sum(total_amt)/(select Sum(total_amt) from Transactions))*100 as percentage_of_sales,
 (count(case when Qty< 0 then Qty else null end)/sum(Qty))*100 as percentage_of_return from Transactions a
 join prod_cat_info b on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_sub_cat_code
 group by prod_subcat
 order by sum(total_amt)desc

 --Q: For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 
 --    30 days of transactions from max transactions data available in the data?

 --Ans,
 select cust_id,sum(total_amt)Revenue from Transactions
 where cust_id in
 (select customer_id from Customer$
 where datediff(year,convert(date,dob,3),getdate()) between 25 and 35)
 and convert(date,tran_date,3) between dateadd(day,-30,(select max(convert(date,tran_date,3)) from Transactions))
 and (select max(convert(date,tran_date,3)) from Transactions)
 group by cust_id

 --Q: Which product category has seen the max value of returns in the last 3 months of transactions.

 --Ans,
 select top 1 prod_cat, sum(total_amt)Amount from Transactions a
 join prod_cat_info b on a.prod_cat_code=b.prod_cat_code and a.prod_subcat_code=b.prod_sub_cat_code
 where Amount<0 and
 convert(date,tran_date,3) between dateadd(month,-3(select max(convert(date,tran_date,3))from Transactions,
 and (select max(convert(date,tran_date,3)) from transactions)
 group by prod_cat
 order by 2 desc

 --Q: Which store-type sells the maximum products; by value of sales amount and by quantity sold.

 --Ans,
 select Store_type, max(total_amt), max(Qty) from Transactions 
 group by Store_type
 having total_amt = (select sum(total_amt) from Transactions group by store_type)
 AND
 Qty = (select sum(Qty) from Transactions group by Store_type)


 
 

 
 

 
 












